apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookstore-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/CONtR0LL3R/bookstore-api.git
    targetRevision: main
    path: bookstore-chart
    helm:
      valuesFiles:
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true