apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookstore-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/CONtR0LL3R/bookstore-api.git
    targetRevision: argo        # ← Changed to argo branch
    path: bookstore-chart
    helm:
      valuesFiles:
        - values-staging.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true