server.port=${SERVER_PORT:8080}
spring.application.name=${APP_NAME:BookStore API}

# Database Connection Details
spring.datasource.url=jdbc:postgresql://postgres-service:5432/bookstoredb
spring.datasource.username=${DB_USERNAME:bookstoreuser}
spring.datasource.password=${DB_PASSWORD:bookstorepass123}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

logging.level.org.hibernate=DEBUG
logging.level.com.zaxxer.hikari=DEBUG
logging.level.org.springframework.boot.autoconfigure=DEBUG

debug=true