apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /api(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Values.bookstore.name }}-service
                port:
                  number: {{ .Values.bookstore.service.port }}
          - path: /()(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Values.frontend.name }}-service
                port:
                  number: {{ .Values.frontend.port }}