{{- if .Values.bookstore_v2 }}
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: bookstore-destination-rule
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  host: bookstore-service
  subsets:
    - name: v1
      labels:
        version: v1
    - name: v2
      labels:
        version: v2
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: bookstore-gateway
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "dev.bookstore.local"
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: bookstore-virtual-service
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  hosts:
    - "dev.bookstore.local"
  gateways:
    - bookstore-gateway
  http:
    - route:
        - destination:
            host: bookstore-service
            subset: v1
          weight: 90
        - destination:
            host: bookstore-service
            subset: v2
          weight: 10
  {{- end }}