apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.headless_service_name }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  clusterIP: None
  selector:
    app: {{ .Values.postgres.name }}
  ports:
    - port: {{ .Values.postgres.port }}
      targetPort: {{ .Values.postgres.port }}